import { EventEmitter } from 'eventemitter3';

const emitter = new EventEmitter();

const EventTypes = {
  ADD_BUTTON_CLICKED: 'addButtonClicked',
  OPEN_FILE_BROWSER: 'openFileBrowser',
  ADD_FILE_TO_LIBRARY: 'addFileToLibrary',
  EDIT_SEMINAR: 'editSeminar',
  ADD_FILE_TO_EVENT: 'addFileToEvent',
  UPDATE_TIME_MANAGERMENT: 'updateTimeManagermanent',
  EDIT_USER_DETAIL: 'EDIT_USER_DETAIL',
  EDIT_LIBRARY: 'EDIT_LIBRARY',
  CONFIRM_EDIT_SEMINAR: 'CONFIRM_EDIT_SEMINAR',

  CONFIRM_NOTE_TEXT: 'CONFIRM_NOTE_TEXT',
  CONFIRM_ADD_DOCUMENT_MATERIAL: 'CONFIRM_ADD_DOCUMENT_MATERIAL',
  ADD_FILE_TO_CHECKIN: 'ADD_FILE_TO_CHECKIN',
  CHANGE_TYPE_NOTE: 'CHANGE_TYPE_NOTE',
  REFRESS_REMINDER_LIST: 'REFRESS_REMINDER_LIST',
  ADD_FILE_TO_NOTE: 'ADD_FILE_TO_NOTE',
  CONFIRM_ADD_FOLDER: 'CONFIRM_ADD_FOLDER',

  CHANGE_TAB_CHECK_IN_DETAIL: 'CHANGE_TAB_CHECK_IN_DETAIL',
  SHOW_CHECKIN_UPLOAD_BUTTON: 'SHOW_CHECKIN_UPLOAD_BUTTON',
  ADD_FILE_TO_ITINERAEY_MGT: 'ADD_FILE_TO_ITINERAEY_MGT',

  UPDATE_ACCOUNT_DETAIL: 'UPDATE_ACCOUNT_DETAIL',
  EDIT_EVENTPPT: 'EDIT_EVENTPPT',
  DELETE_EVENTPPT: 'DELETE_EVENTPPT',
  RERENDER_HEADER: 'RERENDER_HEADER',
  EDIT_SEATING_PLAN_TYPE: 'EDIT_SEATING_PLAN_TYPE',
  SELECT_PLAN_TYPE: 'SELECT_PLAN_TYPE',
  DELETE_PLAN_TYPE: 'SELECT_PLAN_TYPE',
  EDIT_SEATING_PLAN: 'EDIT_SEATING_PLAN',
  PLAN2PDF: 'PLAN2PDF',
  CHANGE_HEADER_NOTE_CONTENT: 'CHANGE_HEADER_NOTE_CONTENT',
  MOVE_DATA_TO_ADD_FOLDER: 'MOVE_DATA_TO_ADD_FOLDER',
  EDIT_COMPANY: 'EDIT_COMPANY',
  ADD_CSV_FILE: 'ADD_CSV_FILE',
  EDIT_STUDENT: 'EDIT_STUDENT',
  ADD_COMPANIES_ACCOUNTMGT: 'ADD_COMPANIES_ACCOUNTMGT',
  SHOW_SEMINAR_SEARCH: 'SHOW_SEMINAR_SEARCH',

  ADD_STUDENT_COMPANY: 'ADD_STUDENT_COMPANY',
  SELECT_ALL_STUDENTS_COMPANY: 'SELECT_ALL_STUDENTS_COMPANY',
  CLEAR_ALL_STUDENTS_COMPANY: 'CLEAR_ALL_STUDENTS_COMPANY',

  ADD_STUDENT: 'ADD_STUDENT',
  ADD_SEMINAR_TO_USER: 'ADD_SEMINAR_TO_USER',

  CHANGE_TAB_COMPANY: 'CHANGE_TAB_COMPANY',

  EXPORT_CONFERENCE_STUDENTS_ATTENDANCE: 'EXPORT_CONFERENCE_STUDENTS_ATTENDANCE',

  SEND_QR_CODE_TO_STUDENTS: 'SEND_QR_CODE_TO_STUDENTS',
  SEND_QR_CODE_TO_INDIVIDUAL_STUDENTS: 'SEND_QR_CODE_TO_INDIVIDUAL_STUDENTS',
  ADD_USER_ITINERARY: 'ADD_USER_ITINERARY',
  DIRECTION_CONTRACT: 'DIRECTION_CONTRACT',
  DELETE_ALL_CONFERENCE_STUDENTS: 'DELETE_ALL_CONFERENCE_STUDENTS',
  UPDATE_TITLE_NOTE:'UPDATE_TITLE_NOTE',
  DELETE_ALL_STUDENTS_COMPANY: 'DELETE_ALL_STUDENTS_COMPANY',
  BACK_TO_LIST_SEMINAR_BEFORE:'BACK_TO_LIST_SEMINAR_BEFORE',
  RESET_SYSTEM_DEFAULT: 'RESET_SYSTEM_DEFAULT'
};

export { emitter, EventTypes };
